from typing import Dict, Any


def build_payload(context: Dict[str, Any]) -> Dict[str, Any]:

    project = context.get("project")
    user = context.get("user")
    plan = context.get("plan")
    client = context.get("client")
    chart32 = context.get("chart32")
    chart16 = context.get("chart16")
    request_data = context.get("request_data", {})
    sp_logo_url = context.get("sp_logo_url", "")
    lang =  context.get("lang", "en")

    # Raw room polygons (kept for backward compatibility if needed)
    rooms = context.get("rooms", [])

    # Rule engine output
    ratings = context.get("ratings", {})
    rating_rows = ratings.get("rows", []) if isinstance(ratings, dict) else []

    # Pull the directions lookup map we created in get_report_context
    directions_lookup = context.get("directions_lookup", {})

    return {
        # ================= CONSULTANT =================
        "is_whitelabel": bool(getattr(plan, "is_whitelabel", False)),
        "consultant": {
            "name": getattr(user, "full_name", "Dr. Amrutha Amberkar") if user else "",
            "title": getattr(user, "role", "Phd. Vastu Consultant") if user else ""
        },

        # ================= CLIENT =================
        "client": {
            "name": client.get("name", "") if isinstance(client, dict) else ""
        },

        # ================= PROJECT =================
        "project": {
            "name": getattr(project, "name", "") if project else "",
            "type": getattr(project, "property_type", "") if project else ""
        },

        # ================= PROPERTY =================
        "property": {
            "type": getattr(project, "property_type", "") if project else "",
            
            # DYNAMIC FALLBACKS: Use request_data if available, otherwise pull from our lookup!
            "entrance": request_data.get("entrance") or directions_lookup.get("main entrance", "Not Specified"),
            "entrance_class": request_data.get("entrance_class", "good"),
            
            "kitchen": request_data.get("kitchen") or directions_lookup.get("kitchen", "Not Specified"),
            "kitchen_class": request_data.get("kitchen_class", "warning"),
            
            "master_bedroom": request_data.get("master_bedroom") or directions_lookup.get("master bedroom", "Not Specified"),
            "bedroom_class": request_data.get("bedroom_class", "good"),
            
            "concern": request_data.get("concern", ""),
            "concern_class": request_data.get("concern_class", "bad"),
        },

        # ================= SCORE =================
        "score": {
            "overall": ratings.get("overall", 0) if isinstance(ratings, dict) else 0
        },

        # ================= ROOMS =================
        "rooms": [
            {
                "name": row.get("name", ""),
                "direction": row.get("direction", ""),
                "status": row.get("status", row.get("state", "")),
                "color": row.get("color", ""),
                "remedy": row.get("remedy", ""),
                "description": row.get("description", ""),
                "therapy": row.get("therapy", ""),
                "rating": row.get("rating", 0),
                "type": row.get("type", "")
            }
            for row in rating_rows
        ],

        # ================= RULE ENGINE OUTPUT =================
        "ratings": rating_rows,

        # ================= MEDIA =================
        "logo_url": request_data.get("logo_url", sp_logo_url),
        "chart32_url": chart32,
        "chart16_url": chart16,
        "lang":lang,

        # ================= FOOTER =================
        "footer": {
            "note": "Generated by Spiritualhub" # Fixed typo here too!
        }
    }