from typing import Dict, Any


def build_payload(context: Dict[str, Any]) -> Dict[str, Any]:

    project = context.get("project")
    user = context.get("user")
    client = context.get("client")
    request_data = context.get("request_data", {})

    rooms = context.get("rooms", [])

    # 🔥 SINGLE SOURCE OF TRUTH (Rule Engine Output)
    ratings = context.get("ratings", {})

    return {
        # ================= CONSULTANT =================
        "consultant": {
            "name": getattr(user, "full_name", "Dr. Amrutha Amberkar") if user else "",
            "title": getattr(user, "role", "Phd. Vastu Consultant") if user else ""
        },

        # ================= CLIENT =================
        "client": {
            "name": client.get("name", "") if isinstance(client, dict) else ""
        },

        # ================= PROJECT =================
        "project": {
            "name": getattr(project, "name", "") if project else "",
            "type": getattr(project, "property_type", "") if project else ""
        },

        # ================= PROPERTY =================
        "property": {
            "type": getattr(project, "property_type", "") if project else "",
            "entrance": request_data.get("entrance", ""),
            "entrance_class": request_data.get("entrance_class", "good"),
            "kitchen": request_data.get("kitchen", ""),
            "kitchen_class": request_data.get("kitchen_class", "warning"),
            "master_bedroom": request_data.get("master_bedroom", ""),
            "bedroom_class": request_data.get("bedroom_class", "good"),
            "concern": request_data.get("concern", ""),
            "concern_class": request_data.get("concern_class", "bad"),
        },

        # ================= SCORE =================
        "score": {
            "overall": ratings.get("overall", 0) if isinstance(ratings, dict) else 0
        },

        # ================= ROOMS =================
        "rooms": [
            {
                "name": r.name,
                "direction": r.direction,
                "status": getattr(r, "status", ""),
                "color": getattr(r, "color", ""),
                "remedy": getattr(r, "remedy", "")
            }
            for r in rooms
        ],

        # ================= RULE ENGINE OUTPUT =================
        # This replaces analysis + remedies + old ratings
        "ratings": ratings.get("rows", []) if isinstance(ratings, dict) else [],

        # ================= MEDIA =================
        "logo_url": request_data.get("logo_url", ""),
        "chart_url": request_data.get("chart_url", ""),

        # ================= FOOTER =================
        "footer": {
            "note": "Generated by Vastu SaaS Engine"
        }
    }