"""add description to project

Revision ID: 53c5b463e976
Revises: c9bdb018f59d
Create Date: 2026-05-01 18:29:40.824985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53c5b463e976'
down_revision: Union[str, Sequence[str], None] = 'c9bdb018f59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('rotation', sa.Integer(), nullable=True))
    op.alter_column('projects', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'rotation_angle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('rotation_angle', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'rotation')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
