"""fix_floorplan_models

Revision ID: 66866c4f5023
Revises: 29dd5bad4df6
Create Date: 2026-05-13 00:06:48.257809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66866c4f5023'
down_revision: Union[str, Sequence[str], None] = '29dd5bad4df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polygons')
    op.drop_table('project_images')
    op.drop_table('canvas_states')
    op.alter_column('projects', 'status',
               existing_type=mysql.ENUM('UPLOADED', 'BOUNDARY_DRAWN', 'ROOMS_MARKED', 'OBJECTS_MARKED', 'REPORT_GENERATED'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('UPLOADED', 'BOUNDARY_DRAWN', 'ROOMS_MARKED', 'OBJECTS_MARKED', 'REPORT_GENERATED'),
               existing_nullable=True)
    op.create_table('canvas_states',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zoom', mysql.FLOAT(), nullable=True),
    sa.Column('pan_x', mysql.FLOAT(), nullable=True),
    sa.Column('pan_y', mysql.FLOAT(), nullable=True),
    sa.Column('rotation', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('canvas_states_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('project_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_images_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('polygons',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('OUTER_BOUNDARY', 'ROOM', 'OBJECT'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coordinates', mysql.JSON(), nullable=False),
    sa.Column('centroid', mysql.JSON(), nullable=True),
    sa.Column('direction', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('direction_angle', mysql.FLOAT(), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('extra_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['polygons.id'], name=op.f('polygons_ibfk_1')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('polygons_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
