"""add_error_field_to_tasks

Revision ID: 6b5c8cda7e21
Revises: 4dcd90481c8c
Create Date: 2026-05-16 20:38:03.628898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b5c8cda7e21'
down_revision: Union[str, Sequence[str], None] = '4dcd90481c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'task_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_column('tasks', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error_message', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'error')
    # ### end Alembic commands ###
