"""add_client_name_to_project

Revision ID: e08051d3ab00
Revises: fedd64d6d985
Create Date: 2026-05-18 05:26:23.760718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08051d3ab00'
down_revision: Union[str, Sequence[str], None] = 'fedd64d6d985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rule_lookup', 'rules', ['entity_type', 'entity_name', 'direction_system', 'direction_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rule_lookup', table_name='rules')
    # ### end Alembic commands ###
