"""add_client_name_to_project

Revision ID: fedd64d6d985
Revises: 6b5c8cda7e21
Create Date: 2026-05-17 20:51:37.991656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedd64d6d985'
down_revision: Union[str, Sequence[str], None] = '6b5c8cda7e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.add_column('rules', sa.Column('ratings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'ratings')
    op.drop_column('projects', 'client_name')
    # ### end Alembic commands ###
